#pragma once
//ENUM형 사용파일

enum TEXTYPE
{
	TEXTYPE_NORMAL,
	TEXTYPE_CUBE,
};

enum BUFFERTYPE
{
	BUFFERTYPE_TRICOL,
	BUFFERTYPE_RCCOL,
	BUFFERTYPE_RCTEX,
	BUFFERTYPE_CUBE,
	BUFFERTYPE_TERRAIN
};
enum BOUNDTYPE
{
	BOUNDTYPE_SPHERE,
	BOUNDTYPE_CUBE,
};
enum MESHTYPE
{
	MESHTYPE_STATIC,
	MESHTYPE_DYNAMIC,
	MESHTYPE_END

};
enum WINMODE { WINMODE_FULL, WINMODE_WIN };
enum ANGLE { ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END };
enum CAMMODE { CAMMODE_DYNAMIC, CAMMODE_STATIC, CAMMODE_GAME, CAMMODE_END };
enum SORTID { SORTID_FIRST, SORTID_NORMAL, SORTID_LAST, SORTID_END };
enum TERRIAN_INSERTTYPE
{
	INSERTTYPE_NUMBER,
	INSERTTYPE_ENGLISH,
};

//10 /11일 추가
enum THREADMENU
{
	THREAD_MOUSE,//마우스에 관련된 스레드 인덱스

	THREAD_END,
}THREAD_MENU;